[package]
name = "kernel_devfs"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel_device = { path = "../kernel_device" }
kernel_vfs = { path = "../kernel_vfs" }

log.workspace = true
spin.workspace = true
thiserror.workspace = true