[package]
name = "window_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel_api = { path = "../../kernel/api" }
std = { version = "0.1.0", path = "../std" }
