[package]
name = "muffin_libc"
version = "0.1.0"
edition = "2024"

[lib]
test = false

[dependencies]
muffin_libc_spec_comment = { path = "muffin_libc_spec_comment" }

[build-dependencies]
cbindgen = "0.29"
walkdir = "2.5"