[package]
name = "devos"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none", default-features = false }
kernel_test = { path = "kernel_test", artifact = "bin", target = "x86_64-unknown-none", default-features = false }

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = [
    "kernel",
    "kernel_api",
    "kernel_test",
    "kernel_test_framework",
    "kernel_test_framework/derive",
    "std",
    "driver/graphics",
    "driver/ide",
    "driver/pci",
    "driver/vga",
]

[features]
default = ["uefi"]
bios = ["kernel/bios"]
uefi = ["kernel/uefi"]