[package]
name = "devos"
version = "0.1.0"
edition = "2024"

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none", default-features = false }
ovmf-prebuilt = "0.2.2"

[workspace]
members = [
    "kernel",
    "kernel/crates/virtual_memory_manager",
    "kernel/crates/physical_memory_manager",
]
default-members = [
    ".",
    "kernel/crates/virtual_memory_manager",
    "kernel/crates/physical_memory_manager",
]

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[workspace.dependencies]
acpi = "5.1"
bitfield = "0.19"
conquer-once = { version = "0.4", default-features = false }
derive_more = { version = "1.0.0", default-features = false, features = ["constructor"] }
jiff = { version = "0.2", default-features = false, features = ["alloc"] }
limine = "0.4"
linked_list_allocator = "0.10"
log = "0.4"
seq-macro = "0.3"
spin = "0.9"
thiserror = { version = "2.0", default-features = false }
uart_16550 = "0.3"
volatile = { version = "0.6", features = ["derive"] }
x86_64 = "0.15"
