[package]
name = "devos"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootloader = "0.11.7" # make sure this is compatible with bootloader_api in [workspace.dependencies]
fs_extra = "1.3.0"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none", default-features = false }
hello_world = { path = "userspace/hello_world", artifact = "bin", target = "x86_64-unknown-none" }
test_kernel_multitasking = { path = "tests/test_kernel_multitasking", artifact = "bin", target = "x86_64-unknown-none" }
test_kernel_unittests = { path = "tests/test_kernel_unittests", artifact = "bin", target = "x86_64-unknown-none" }
test_kernel_vfs = { path = "tests/test_kernel_vfs", artifact = "bin", target = "x86_64-unknown-none" }
test_kernel_vmobject = { path = "tests/test_kernel_vmobject", artifact = "bin", target = "x86_64-unknown-none" }
test_kernel_file_vmobject = { path = "tests/test_kernel_file_vmobject", artifact = "bin", target = "x86_64-unknown-none" }
window_server = { path = "userspace/window_server", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
clap = { version = "4", features = ["derive"] }
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"
rand = "0.9.0-beta.0"

[workspace]
members = [
    "kernel",
    "kernel/api",
    "kernel/foundation",
    "kernel/netstack",
    "kernel_test_framework",
    "kernel_test_framework/derive",
    "userspace/hello_world",
    "userspace/std",
    "userspace/window_server",
]
default-members = [
    ".",
    "kernel/api",
    "kernel/foundation",
    "kernel/netstack",
]

[workspace.dependencies]
acpi = "5.0.0"
bitfield = "0.17.0"
bitflags = "2.4.1"
bootloader_api = "0.11.7"
bresenham = "0.1.1"
conquer-once = { version = "0.4.0", default-features = false }
cordyceps = "0.3.2"
crossbeam = { version = "0.8.4", default-features = false, features = ["alloc", "nightly", "crossbeam-queue"] }
delegate = "0.13.1"
derive_more = { version = "1.0.0", default-features = false, features = ["display", "from", "deref", "deref_mut", "constructor"] }
elfloader = "0.16.0"
foundation = { path = "kernel/foundation" }
futures = { version = "0.3.31", default-features = false, features = ["alloc"] }
kernel_api = { path = "kernel/api" }
kernel_test_framework = { path = "kernel_test_framework" }
linked_list_allocator = "0.10.5"
linkme = "0.3.31"
log = "0.4.22"
mkfs-ext2 = { git = "https://github.com/tsatke/mkfs" }
mkfs-filesystem = { git = "https://github.com/tsatke/mkfs" }
netstack = { path = "kernel/netstack" }
num_enum = { version = "0.7.0", default-features = false }
raw-cpuid = { version = "11.0", default-features = false }
spin = "0.9.8"
thiserror = { version = "2.0.3", default-features = false }
uart_16550 = "0.3"
volatile = { version = "0.6.1", features = ["derive"] }
x2apic = "0.4"
x86_64 = "0.14"

[features]
default = []
