[package]
name = "devos"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none", default-features = false }
hello_world = { path = "userspace/hello_world", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
clap = { version = "4", features = ["derive"] }
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"
proc-macro2 = "1.0.66" # override 1.0.56 which doesn't work on nightly anymore

[workspace]
members = [
    "kernel",
    "kernel_api",
    "std",
    "driver/graphics",
    "driver/ide",
    "driver/pci",
    "driver/vga",
    "userspace/hello_world",
]

[workspace.dependencies]
acpi = "5.0.0"
bitflags = "2.4.1"
bootloader_api = "0.11"
conquer-once = { version = "0.4.0", default-features = false }
derive_more = "0.99.17"
elfloader = "0.16.0"
graphics = { path = "driver/graphics" }
ide = { path = "driver/ide" }
kernel_api = { path = "kernel_api" }
linked_list_allocator = "0.10.5"
mkfs-ext2 = { git = "https://github.com/tsatke/mkfs" }
mkfs-filesystem = { git = "https://github.com/tsatke/mkfs" }
num_enum = { version = "0.7.0", default-features = false }
pci = { path = "driver/pci" }
raw-cpuid = { version = "11.0", default-features = false }
spin = "0.9.8"
uart_16550 = "0.3"
vga = { path = "driver/vga" }
x2apic = "0.4"
x86_64 = "0.14"

[features]
default = []
