[package]
name = "devos"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none", default-features = false }
hello_world = { path = "userspace/hello_world", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
clap = { version = "4", features = ["derive"] }
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"
proc-macro2 = "1.0.66" # override 1.0.56 which doesn't work on nightly anymore

[workspace]
members = [
    "kernel",
    "kernel_api",
    "std",
    "driver/graphics",
    "driver/ide",
    "driver/pci",
    "driver/vga",
    "userspace/hello_world",
]

[features]
default = []
