[package]
name = "sandbox_nostd"
version = "0.1.0"
edition = "2024"

[build-dependencies]
libmuffin = { path = "../libmuffin", artifact = "staticlib", target = "x86_64-unknown-muffin" }

[dependencies]
x86_64.workspace = true