load("@rules_rust//rust:defs.bzl", "rust_library")
load("//bazel:kernel_crates.bzl", "crate_label")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "minilib",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    deps = [
        "//kernel/abi",
        crate_label("linked_list_allocator"),
    ],
)
