load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "fbdemo",
    srcs = ["src/main.rs"],
    edition = "2024",
    platform = "//platforms:x86_64-none",
    deps = [
        "//kernel/abi",
        "//userspace/libs/gfx",
        "//userspace/minilib",
    ],
)
