include_guard = "STDINT_H"
language = "C"
no_includes = true

[export]
include = [
    "int8_t",
    "uint8_t",
    "int_least8_t",
    "uint_least8_t",
    "int8_fast_t",
    "uint8_fast_t",
    "int16_t",
    "uint16_t",
    "int_least16_t",
    "uint_least16_t",
    "int_fast16_t",
    "uint_fast16_t",
    "int32_t",
    "uint32_t",
    "int_least32_t",
    "uint_least32_t",
    "int_fast32_t",
    "uint_fast32_t",
    "int64_t",
    "uint64_t",
    "int_least64_t",
    "uint_least64_t",
    "int_fast64_t",
    "uint_fast64_t",
    "int128_t",
    "uint128_t",
    "int_least128_t",
    "uint_least128_t",
    "int_fast128_t",
    "uint_fast128_t",
    "intptr_t",
    "uintptr_t",
    "intmax_t",
    "uintmax_t",
    "short",
    "int",
    "long",
    "longlong",
]