[package]
name = "signals-test-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel = { path = "../../../../kernel" }
kernel_vfs = { path = "../../../../kernel/crates/kernel_vfs" }
kernel_device = { path = "../../../../kernel/crates/kernel_device" }

mkfs-ext2.workspace = true
mkfs-filesystem.workspace = true
log.workspace = true
spin.workspace = true
x86_64.workspace = true
