[package]
name = "vga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bresenham.workspace = true
conquer-once.workspace = true
graphics.workspace = true
spin.workspace = true
