[package]
name = "kernel_pci"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel_memapi = { path = "../kernel_memapi" }

log.workspace = true
spin.workspace = true
thiserror.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64.workspace = true
