[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acpi.workspace = true
bitfield.workspace = true
bitflags.workspace = true
bootloader_api.workspace = true
conquer-once.workspace = true
cordyceps.workspace = true
crossbeam-queue.workspace = true
derive_more.workspace = true
elfloader.workspace = true
kernel_api.workspace = true
kernel_test_framework.workspace = true
linked_list_allocator.workspace = true
linkme.workspace = true
mkfs-ext2.workspace = true
mkfs-filesystem.workspace = true
num_enum.workspace = true
raw-cpuid.workspace = true
spin.workspace = true
uart_16550.workspace = true
volatile.workspace = true
x2apic.workspace = true
x86_64.workspace = true

[features]
default = []
kernel_test = []
