[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acpi = "4.1.1"
bootloader_api = "0.11"
conquer-once = { version = "0.4.0", default-features = false }
graphics = { path = "../driver/graphics" }
ide = { path = "../driver/ide" }
kernel_api = { path = "../kernel_api" }
kernel_test_framework = { path = "../kernel_test_framework" }
linked_list_allocator = "0.10.5"
linkme = "0.3.9"
num_enum = { version = "0.6.1", default-features = false }
pci = { path = "../driver/pci" }
raw-cpuid = { version = "11.0.0", default-features = false }
spin = "0.9.8"
uart_16550 = "0.2.18"
vga = { path = "../driver/vga" }
x2apic = "0.4.2"
x86_64 = "0.14.10"

[features]
default = ["uefi"]
bios = []
uefi = []
