include_guard = "SYS_TYPES_H"
language = "C"
no_includes = true

[export]
include = [
    "blkcnt_t",
    "blksize_t",
    "clock_t",
    "clockid_t",
    "dev_t",
    "fsblkcnt_t",
    "fsfilcnt_t",
    "gid_t",
    "id_t",
    "ino_t",
    "key_t",
    "mode_t",
    "nlink_t",
    "off_t",
    "pid_t",
    "pthread_attr_t",
    "pthread_barrier_t",
    "pthread_barrierattr_t",
    "pthread_cond_t",
    "pthread_condattr_t",
    "pthread_key_t",
    "pthread_mutex_t",
    "pthread_mutexattr_t",
    "pthread_once_t",
    "pthread_rwlock_t",
    "pthread_rwlockattr_t",
    "pthread_spinlock_t",
    "pthread_t",
    "reclen_t",
    "size_t",
    "ssize_t",
    "suseconds_t",
    "time_t",
    "timer_t",
    "uid_t",
]