[package]
name = "foundation"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam.workspace = true
delegate.workspace = true
derive_more.workspace = true
futures.workspace = true
spin.workspace = true