[package]
name = "kernel_syscall"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel_abi = { path = "../kernel_abi" }
kernel_vfs = { path = "../kernel_vfs" }

log.workspace = true
spin.workspace = true
thiserror.workspace = true