[package]
name = "std"
version = "0.1.0"
edition = "2021"
description = "The standard library for DevOS."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel_api = { path = "../kernel/api" }