name: build

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 5,17 * * *' # every day because of the rust nightly version

jobs:

  test:
    name: Test ${{ matrix.mode }}

    strategy:
      fail-fast: false
      matrix:
        mode: [ '', '--release' ]
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy, llvm-tools-preview, rust-src
          profile: default

      # install QEMU
      - name: Install QEMU
        run: sudo apt update && sudo apt install qemu-system-x86
      - name: "Print QEMU Version"
        run: qemu-system-x86_64 --version

      - name: Build and run all tests
        run: cargo test --workspace ${{ matrix.mode }}

  check-feature-compat:
    name: Check feature compatibility
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy, llvm-tools-preview, rust-src
          profile: default
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - name: Check
        run: cargo hack check --feature-powerset --no-dev-deps

  build:
    name: Build
    needs: [ test, check-feature-compat ]

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy, llvm-tools-preview, rust-src
          profile: default

      - name: Build in release mode
        run: cargo build --release

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: devos-image
          path: target/release/build/devos-*/out/*.img
          if-no-files-found: error